# docker-compose.yml
version: "3.8"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - /mnt/hd/midea:/data
    ports:
      - "8096:8096" # Acesso à interface web
      - "8920:8920" # Opcional: Acesso HTTPS à interface web
      - "1900:1900/udp" # DLNA
      - "7359:7359/udp" # Descoberta de clientes
    restart: unless-stopped