# docker-compose.yml
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: Dashy
    
    # Mapeia o arquivo de configuração da pasta atual para dentro do container
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
      
      # Volumes para monitoramento do sistema (leitura apenas)
      # Essencial para os widgets de desempenho do notebook
      - /proc/stat:/proc/stat:ro
      - /proc/meminfo:/proc/meminfo:ro
      - /:/media/disk:ro # Mapeia o disco para o widget de armazenamento
    
    ports:
      - 80:8080 # A porta 80 do seu notebook aponta para a porta 8080 do Dashy
      
    environment:
      - NODE_ENV=production
      
    restart: unless-stopped